### PR TITLE
Resubmitting Found Typo

### PR DESCRIPTION
**Pull request by slycozzolino**
I believe I accidentally selected the wrong branch and it wouldn't let me send to your master branch so I just closed it.

### CODE REVIEW

**Comment by redwolf2** [comment]
Added the german translation and merged your changes https://github.com/NPBruce/valkyrie-questdata/pull/17

**Comment by redwolf2** [comment]
Merged updates in https://github.com/NPBruce/valkyrie-questdata/pull/17

**Comment by NPBruce** [comment]
I merged #17 because I understood that included these changes, but it appears not to have included them all and of course now this is in conflict.

**Comment by slycozzolino** [comment]
Ok these were minor changes. I believe they are resolved in 17 I will close this pull request and delete my local copy. I can copy the latest published file and work from there if I finds something that didn't make it in.

**Pull request closed without merging**
