### PR TITLE
Slycozzdev

### PR DESCRIPTION
**Pull request by slycozzolino**
Made minor updates to add difficulty and scenario icon. Can you please republish?

### CODE REVIEW

**Comment by NPBruce** [comment]
No problem.

PS: Forgot to mention that this repo is marked as CC0 (public domain), so publishing here will apply this licence, just to ensure that you know this.

**Comment by NPBruce** [comment]
A few comments you might want to consider:

* The Monster Activations you are using are depricated.  They will work, but next time you are working on this consider changing them to the newer event system so that they will continue to work going forward
* When giving items (like the Brass Key) you get use a QItem and add it to show the image of the item next to the event
* Your test notation is some times a little different to FFG notation in the rules

**Comment by slycozzolino** [comment]
I just started adding item images and will fix activations.

Can you give me and example of notations that i should look for?

Thanks,
Michael


NPBruce <notifications@github.com> wrote:


A few comments you might want to consider:

  *   The Monster Activations you are using are depricated. They will work, but next time you are working on this consider changing them to the newer event system so that they will continue to work going forward
  *   When giving items (like the Brass Key) you get use a QItem and add it to show the image of the item next to the event
  *   Your test notation is some times a little different to FFG notation in the rules

**Comment by slycozzolino** [comment]
Do you mean tests like
Test your will or something isnt consistent?

Thanks,
Michael


Michael Cozzolino <Sly_Cozzolino@hotmail.com> wrote:

I just started adding item images and will fix activations.

Can you give me and example of notations that i should look for?

Thanks,
Michael


NPBruce <notifications@github.com> wrote:


A few comments you might want to consider:

  *   The Monster Activations you are using are depricated. They will work, but next time you are working on this consider changing them to the newer event system so that they will continue to work going forward
  *   When giving items (like the Brass Key) you get use a QItem and add it to show the image of the item next to the event
  *   Your test notation is some times a little different to FFG notation in the rules

**Comment by NPBruce** [comment]
image

**Comment by NPBruce** [comment]
These examples are good to follow.

**Pull request merged**
