### PR TITLE
New scenario, In Places Unseen

### PR DESCRIPTION
**Pull request by LordPyrex**
I formally submit my scenario in hopes that it will provide some modicum of enjoyment to my fellow Mansions of Madness players.

### CODE REVIEW

**Comment by NPBruce** [comment]
I have manually added this with two changes:

https://github.com/NPBruce/valkyrie-questdata/commit/6ceba70fa230ea871b4500d63befe3cceafd4272

1: I have removed the spaces from the path, package name and thumbnail image.  This is required for internet downloads to not break.

2: I have extracted the package for valkyrie-questdata, the package is built into valkyrie-store.  This will change in 1.4 where authors will have direct control over their packages, but for now the source control needs the extracted files.

Something else to consider is that Chtuhlu.png is a very large file, you might want to resize or recompress it (jpg is probably a better option for non-text images without transparency).

**Comment by LordPyrex** [comment]
Thanks Bruce,

I'll go ahead and take care of that file now. Am I able to change that
info, or would you rather I do a resubmit of the package?

**Comment by NPBruce** [comment]
Simplest thing would be to take my copy (merge, refork or just copy) and modify then do another pull request with any changes you want.  Submit the changes on the individual files rather than a built package.

**Comment by NPBruce** [comment]
FYI i just did another small change,

https://github.com/NPBruce/valkyrie-questdata/commit/c5d05ba6aa497671f91bc70232aaf89c2188e7ae

I missed that the thumbnail image was also used inside the quest.

**Comment by LordPyrex** [comment]
I think I may have made a mistake and forgot to remove chtuhlu.png from the
folder. I went a different direction with my images and just forgot to
remove it. I double checked mu ui.ini and it's not called for in any
display. Can you delete it from the folder to cut back on the data?

**Comment by NPBruce** [comment]
Done 
https://github.com/NPBruce/valkyrie-questdata/commit/5862b0c29a7e115663b269fa258c2fefeb37d483

**Pull request closed without merging**
