### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by EtiCarasoft**
upload quest items

### CODE REVIEW

**Comment by NPBruce** [comment]
This has conflicts because I had to rename the path because the spaces broke the download.  I can't merge this until you make the same change.

**Comment by EtiCarasoft** [comment]
How do i change the path of the folder or name?

**Comment by EtiCarasoft** [comment]
iI have deleted the previous folder and crested a new one with the same name as yours with the updated content.

**Comment by EtiCarasoft** [comment]
It's solved this way?

**Comment by NPBruce** [comment]
Updated

**Pull request merged**
